{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[{"file_id":"1P43VCI2OUXTw8qdnUqbCe4xcPwAJGgH3","timestamp":1732218960095}]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["*   **AÃ±o:** 2024\n","*   **Alumno/a:** Alexey Marassi\n","*   **Legajo:** 19070876"],"metadata":{"id":"UwxQU5JCF33j"}},{"cell_type":"markdown","source":["# Pydantic\n","Pydantic es una libreria rapida y extensible que nos permite validar datos usando tipos de datos de Python.\n"],"metadata":{"id":"8ec8DQdbWQfC"}},{"cell_type":"markdown","source":["Primero, importe `pydantic`."],"metadata":{"id":"uF01w4AQcrtV"}},{"cell_type":"code","source":["import pydantic"],"metadata":{"id":"4WPUcwU_c5n2","executionInfo":{"status":"ok","timestamp":1732220613087,"user_tz":180,"elapsed":366,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}}},"execution_count":1,"outputs":[]},{"cell_type":"markdown","source":["Supongamos que tenemos una lista de clientes (llamemoslo en el codigo `Client`). Los clientes tienen dos campos: DNI (un entero) y nacionalidad (un `string`). Cree el modelo base de `Client` (en forma de clases de Python)."],"metadata":{"id":"eC8fpbQ04GzX"}},{"cell_type":"code","source":["from pydantic import BaseModel\n","class Client(BaseModel):\n","  dni: int\n","  nacionalidad: str"],"metadata":{"id":"I4zJ7s_k4GkI","executionInfo":{"status":"ok","timestamp":1732220759678,"user_tz":180,"elapsed":1053,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}}},"execution_count":3,"outputs":[]},{"cell_type":"markdown","source":["Cree a un usuario con documento 39.755.010 y nacionalidad 'Argentina'. Muestre todos sus campos."],"metadata":{"id":"zas-XX4r4SeP"}},{"cell_type":"code","source":["usuario = Client(dni=39755010, nacionalidad='Argentina')\n","print(usuario)"],"metadata":{"id":"_DhtCWhr4ST9","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1732220822396,"user_tz":180,"elapsed":286,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}},"outputId":"7b2553ba-04c8-49b4-d640-a834661b41a6"},"execution_count":4,"outputs":[{"output_type":"stream","name":"stdout","text":["dni=39755010 nacionalidad='Argentina'\n"]}]},{"cell_type":"markdown","source":["Intente crear al usuario con un documento en forma de `string`. Deberia fallar..."],"metadata":{"id":"ejbn5RSH4S_W"}},{"cell_type":"code","source":["nuevo_usuario = Client(dni='12412', nacionalidad='Argentina')\n","#nuevo_usuario = Client(dni='hola', nacionalidad='Argentina')\n","\n","# falla solo en el caso cuando el dni es exlicitamente un str que tiene letras\n","# si el str consiste de numeros hace la convercion a int\n","\n","print(nuevo_usuario)"],"metadata":{"id":"OMPq8C1C4Su3","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1732221020900,"user_tz":180,"elapsed":284,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}},"outputId":"f23bb55e-9276-41b0-a73b-97568c45c32d"},"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["dni=12412 nacionalidad='Argentina'\n"]}]},{"cell_type":"markdown","source":["Hemos detectado que ciertos clientes tienen nacionalidades que no existen. Ademas, hay numeros de documento negativos y se tiene que poder agregar la fecha de registro de los clientes (que no pueden ser del futuro). Cambiar la definicion del cliente para que estas cosas no ocurran. Despues de la siguiente celda, cree otras 3 mas probando un caso donde deberia funcionar y otros dos en los que no."],"metadata":{"id":"jARZRMfe6MPE"}},{"cell_type":"code","source":["from pydantic import BaseModel, validator, ValidationError\n","from datetime import datetime # para usar datetime\n","# nacionalidad inexistente\n","# dni negativos\n","# poder agregar la fecha del registro < fecha de hoy\n","\n","\n","lista_nacionalidades = ['Argentina',\n","                        'Chile',\n","                        'Uruguay',\n","                        'Paraguay',\n","                        'Bolivia',\n","                        'Peru',\n","                        'Colombia',\n","                        'Venezuela',\n","                        'Ecuador',\n","                        'Guyana',\n","                        'Suriname',\n","                        'Francia']\n","\n","class Client(BaseModel):\n","  dni: int\n","  nacionalidad: str\n","  fecha_registro: datetime\n","\n","  @validator('nacionalidad')\n","  def validar_nacionalidad(cls, valor): #se usa 'cls' en vez de 'self' en pydantic\n","    if valor not in lista_nacionalidades:\n","      raise ValueError('Nacionalidad no esta en la lista de nacionalidades')\n","    return valor\n","\n","  @validator('dni')\n","  def validar_dni(cls, valor):\n","    if valor < 0:\n","      raise ValueError('DNI no puede ser negativo')\n","    return valor\n","\n","  @validator('fecha_registro')\n","  def validar_fecha_registro(cls, valor):\n","    if valor > datetime.now():\n","      raise ValueError('Fecha de registro no puede ser en el futuro')\n","    return valor"],"metadata":{"id":"JWsWZZPH6NFv","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1732221840979,"user_tz":180,"elapsed":262,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}},"outputId":"a09f0025-c93e-4649-8857-2e74a1f55b13"},"execution_count":15,"outputs":[{"output_type":"stream","name":"stderr","text":["<ipython-input-15-acc580f1a839>:26: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/\n","  @validator('nacionalidad')\n","<ipython-input-15-acc580f1a839>:32: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/\n","  @validator('dni')\n","<ipython-input-15-acc580f1a839>:38: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/\n","  @validator('fecha_registro')\n"]}]},{"cell_type":"code","source":["# nacionalidad que no esta en la lista\n","usuario = Client(dni=39755010, nacionalidad='Mexico', fecha_registro=datetime.now())"],"metadata":{"id":"sWyLaqoC7QUK","colab":{"base_uri":"https://localhost:8080/","height":315},"executionInfo":{"status":"error","timestamp":1732221957883,"user_tz":180,"elapsed":280,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}},"outputId":"2522c249-5307-45de-d0d5-4b9d80bca555"},"execution_count":16,"outputs":[{"output_type":"error","ename":"ValidationError","evalue":"1 validation error for Client\nnacionalidad\n  Value error, Nacionalidad no esta en la lista de nacionalidades [type=value_error, input_value='Mexico', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/value_error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)","\u001b[0;32m<ipython-input-16-721a3cd53eba>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0musuario\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mClient\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdni\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m39755010\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnacionalidad\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'Mexico'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfecha_registro\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdatetime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/pydantic/main.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, **data)\u001b[0m\n\u001b[1;32m    210\u001b[0m         \u001b[0;31m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    211\u001b[0m         \u001b[0m__tracebackhide__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 212\u001b[0;31m         \u001b[0mvalidated_self\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__pydantic_validator__\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalidate_python\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself_instance\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    213\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mvalidated_self\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    214\u001b[0m             warnings.warn(\n","\u001b[0;31mValidationError\u001b[0m: 1 validation error for Client\nnacionalidad\n  Value error, Nacionalidad no esta en la lista de nacionalidades [type=value_error, input_value='Mexico', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/value_error"]}]},{"cell_type":"code","source":["# dni negativo\n","usuario = Client(dni=-39755010, nacionalidad='Argentina', fecha_registro=datetime.now())"],"metadata":{"id":"E6h_7zb77QhN","colab":{"base_uri":"https://localhost:8080/","height":332},"executionInfo":{"status":"error","timestamp":1732222013544,"user_tz":180,"elapsed":296,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}},"outputId":"ac518007-edab-4791-98b6-08fbe476a511"},"execution_count":18,"outputs":[{"output_type":"error","ename":"ValidationError","evalue":"1 validation error for Client\ndni\n  Value error, DNI no puede ser negativo [type=value_error, input_value=-39755010, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.9/v/value_error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)","\u001b[0;32m<ipython-input-18-eda5246613a3>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# dni negativo\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0musuario\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mClient\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdni\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m39755010\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnacionalidad\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'Argentina'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfecha_registro\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdatetime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/pydantic/main.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, **data)\u001b[0m\n\u001b[1;32m    210\u001b[0m         \u001b[0;31m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    211\u001b[0m         \u001b[0m__tracebackhide__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 212\u001b[0;31m         \u001b[0mvalidated_self\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__pydantic_validator__\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalidate_python\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself_instance\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    213\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mvalidated_self\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    214\u001b[0m             warnings.warn(\n","\u001b[0;31mValidationError\u001b[0m: 1 validation error for Client\ndni\n  Value error, DNI no puede ser negativo [type=value_error, input_value=-39755010, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.9/v/value_error"]}]},{"cell_type":"code","source":["# nacionalidad que no esta en la lista\n","usuario = Client(dni=39755010, nacionalidad='Argentina', fecha_registro='2030-01-05')"],"metadata":{"id":"MtDGMxri7R_O","colab":{"base_uri":"https://localhost:8080/","height":332},"executionInfo":{"status":"error","timestamp":1732222078161,"user_tz":180,"elapsed":269,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}},"outputId":"2adb5be6-3d7c-4868-a45f-b11a58973a1d"},"execution_count":21,"outputs":[{"output_type":"error","ename":"ValidationError","evalue":"1 validation error for Client\nfecha_registro\n  Value error, Fecha de registro no puede ser en el futuro [type=value_error, input_value='2030-01-05', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/value_error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)","\u001b[0;32m<ipython-input-21-526b3f22d5ce>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# nacionalidad que no esta en la lista\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0musuario\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mClient\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdni\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m39755010\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnacionalidad\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'Argentina'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfecha_registro\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'2030-01-05'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/pydantic/main.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, **data)\u001b[0m\n\u001b[1;32m    210\u001b[0m         \u001b[0;31m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    211\u001b[0m         \u001b[0m__tracebackhide__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 212\u001b[0;31m         \u001b[0mvalidated_self\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__pydantic_validator__\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalidate_python\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself_instance\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    213\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mvalidated_self\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    214\u001b[0m             warnings.warn(\n","\u001b[0;31mValidationError\u001b[0m: 1 validation error for Client\nfecha_registro\n  Value error, Fecha de registro no puede ser en el futuro [type=value_error, input_value='2030-01-05', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/value_error"]}]},{"cell_type":"markdown","source":["# Pandera\n","Hacer lo que se pidio en la ultima celda anterior, pero con Pandera."],"metadata":{"id":"79P3MNuZ8-t3"}},{"cell_type":"code","source":["!pip install pandera"],"metadata":{"id":"z3DJDdci8-BP","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1732222157395,"user_tz":180,"elapsed":5373,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}},"outputId":"d9ac5767-6234-4997-8976-4c3592a32cfc"},"execution_count":23,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting pandera\n","  Downloading pandera-0.21.0-py3-none-any.whl.metadata (15 kB)\n","Collecting multimethod (from pandera)\n","  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)\n","Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from pandera) (1.26.4)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from pandera) (24.2)\n","Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from pandera) (2.2.2)\n","Requirement already satisfied: pydantic in /usr/local/lib/python3.10/dist-packages (from pandera) (2.9.2)\n","Requirement already satisfied: typeguard in /usr/local/lib/python3.10/dist-packages (from pandera) (4.4.1)\n","Collecting typing-inspect>=0.6.0 (from pandera)\n","  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)\n","Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from pandera) (1.16.0)\n","Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pandera) (2.8.2)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pandera) (2024.2)\n","Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pandera) (2024.2)\n","Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.6.0->pandera)\n","  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)\n","Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.10/dist-packages (from typing-inspect>=0.6.0->pandera) (4.12.2)\n","Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic->pandera) (0.7.0)\n","Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic->pandera) (2.23.4)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pandera) (1.16.0)\n","Downloading pandera-0.21.0-py3-none-any.whl (261 kB)\n","\u001b[2K   \u001b[90mââââââââââââââââââââââââââââââââââââââââ\u001b[0m \u001b[32m261.0/261.0 kB\u001b[0m \u001b[31m6.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)\n","Downloading multimethod-1.12-py3-none-any.whl (10 kB)\n","Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)\n","Installing collected packages: mypy-extensions, multimethod, typing-inspect, pandera\n","Successfully installed multimethod-1.12 mypy-extensions-1.0.0 pandera-0.21.0 typing-inspect-0.9.0\n"]}]},{"cell_type":"code","source":["import pandera as pa\n","import pandas as pd"],"metadata":{"id":"8njRatGxfIqx","executionInfo":{"status":"ok","timestamp":1732224205140,"user_tz":180,"elapsed":971,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}}},"execution_count":44,"outputs":[]},{"cell_type":"code","source":["from pandera import Check\n","from datetime import datetime\n","\n","cliente =  pa.DataFrameSchema(\n","    {\n","        \"dni\": pa.Column(int, Check.greater_than(0)),\n","        \"nacionalidad\": pa.Column(str, Check.isin(lista_nacionalidades)),\n","        \"fecha_registro\": pa.Column(datetime, Check.less_than_or_equal_to(datetime.now()))\n","    }\n",")"],"metadata":{"id":"mCA_eOelfS9f","executionInfo":{"status":"ok","timestamp":1732224205867,"user_tz":180,"elapsed":1,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}}},"execution_count":45,"outputs":[]},{"cell_type":"code","source":["data = {\n","    \"dni\": [19070876, 20567434, -123, 1, 56756],\n","    \"nacionalidad\": ['Argentina', 'Chile', 'Brazil', 'Alemania', 'Colombia'],\n","    \"fecha_registro\": [datetime(1998,1,5),datetime(2000,2,10),datetime(1996,3,1),datetime(1000,10,1),datetime(2300,2,2)]\n","}\n","\n","df = pd.DataFrame(data)\n","\n","# funcion para validar cada registro del df\n","def validar_registro(registro):\n","    try:\n","        cliente.validate(pd.DataFrame([registro])) #validar por fila\n","        print(\"Registro valido:\\n\", registro)\n","        print(\"----------------------------------------------------\")\n","    except pa.errors.SchemaError as e:\n","        print(\"Registro invalido:\\n\", registro)\n","        print(\"----------------------------------------------------\")\n","\n","# iterar sobre las filas del df y validar cada una\n","for index, row in df.iterrows():\n","    validar_registro(row)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"MPSo3gOmii_v","executionInfo":{"status":"ok","timestamp":1732224434663,"user_tz":180,"elapsed":283,"user":{"displayName":"Alex Marassi","userId":"17494825192603200910"}},"outputId":"e05cf473-23de-4217-f2cc-2fb784bef2c7"},"execution_count":52,"outputs":[{"output_type":"stream","name":"stdout","text":["Registro valido:\n"," dni                          19070876\n","nacionalidad                Argentina\n","fecha_registro    1998-01-05 00:00:00\n","Name: 0, dtype: object\n","----------------------------------------------------\n","Registro valido:\n"," dni                          20567434\n","nacionalidad                    Chile\n","fecha_registro    2000-02-10 00:00:00\n","Name: 1, dtype: object\n","----------------------------------------------------\n","Registro invalido:\n"," dni                              -123\n","nacionalidad                   Brazil\n","fecha_registro    1996-03-01 00:00:00\n","Name: 2, dtype: object\n","----------------------------------------------------\n","Registro invalido:\n"," dni                                 1\n","nacionalidad                 Alemania\n","fecha_registro    1000-10-01 00:00:00\n","Name: 3, dtype: object\n","----------------------------------------------------\n","Registro invalido:\n"," dni                             56756\n","nacionalidad                 Colombia\n","fecha_registro    2300-02-02 00:00:00\n","Name: 4, dtype: object\n","----------------------------------------------------\n"]}]}]}